<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Gamja's Interactive Gallery</title>
  <style>
    body {
      display: flex;
      flex-wrap: wrap;
      justify-content: center;
      align-items: center;
      min-height: 100vh;
      background: #f0f0f0;
      margin: 0;
      font-family: Arial, sans-serif;
    }
    h1 {
      width: 100%;
      text-align: center;
      color: #333;
    }
    .card {
      width: 200px;
      height: 300px;
      margin: 20px;
      perspective: 1000px;
      cursor: pointer;
      transition: transform 0.2s;
    }
    .card:hover {
      transform: scale(1.05);
    }
    .card img {
      width: 100%;
      height: 100%;
      object-fit: cover;
      border-radius: 10px;
      box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
      transition: transform 0.1s;
    }
  </style>
</head>
<body>
  <h1>감자의 멋진 순간들</h1>
  <div class="card">
    <img src="https://via.placeholder.com/200x300?text=Gamja1" alt="감자 사진 1">
  </div>
  <div class="card">
    <img src="https://via.placeholder.com/200x300?text=Gamja2" alt="감자 사진 2">
  </div>
  <div class="card">
    <img src="https://via.placeholder.com/200x300?text=Gamja3" alt="감자 사진 3">
  </div>
  <script>
    const cards = document.querySelectorAll('.card');
    cards.forEach(card => {
      card.addEventListener('mousemove', (e) => {
        const rect = card.getBoundingClientRect();
        const x = e.clientX - rect.left;
        const y = e.clientY - rect.top;
        const centerX = rect.width / 2;
        const centerY = rect.height / 2;
        const rotateX = (y - centerY) / 20;
        const rotateY = (centerX - x) / 20;
        card.querySelector('img').style.transform = `rotateX(${rotateX}deg) rotateY(${rotateY}deg)`;
      });
      card.addEventListener('mouseleave', () => {
        card.querySelector('img').style.transform = 'rotateX(0deg) rotateY(0deg)';
      });
    });
  </script>
</body>
</html>
